name: Build and Test C# Project (Framework 4.7.2)

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest

    env:
      MELONLOADER_REPO: https://api.github.com/repos/LavaGang/MelonLoader/releases/latest
      MELONLOADER_ASSET_NAME: MelonLoader.x64.zip

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install 7-Zip
      run: choco install 7zip.install -y

    - name: Create Local Output.7z
      run: |
        7z a Output.7z .

    - name: Use Local Output.7z
      run: |
        # Extract the locally created Output.7z
        7z x Output.7z -oExtractedOutput

        # Verify the extracted files
        ls ExtractedOutput

    - name: Build and Package
      run: |
        if (-not $(git --version 2>$null)) {
            $commitHash = "NOT SET"
        } else {
            $commitHash = git rev-parse --short HEAD
        }

        $timestamp = Get-Date -Format 'o'

        @"
        namespace SinmaiAssist {
            public static partial class BuildInfo {
                public const string CommitHash = "$commitHash";
                public const string BuildDate = "$timestamp";
            }
        }
        "@ | Out-File -FilePath ".\BuildInfo.cs" -Encoding ascii
        dotnet build
        mkdir ".\Out\Mods\"
        mkdir ".\Out\UserLibs\"
        mkdir ".\Out\Sinmai-Assist\"
        cmd /c copy /y ".\ExtractedOutput\Output\Sinmai-Assist.dll" ".\Out\Mods\Sinmai-Assist.dll"
        cmd /c copy /y ".\ExtractedOutput\Output\YamlDotNet.dll" ".\Out\UserLibs\YamlDotNet.dll"
        cmd /c copy /y ".\config - zh_CN.yml" ".\Out\Sinmai-Assist\config.yml"
        Compress-Archive -Path "$(Get-Location)\Out\*" -DestinationPath "$(Get-Location)\Out.zip" -Update

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: artifact
        path: Out.zip
